@extends('saas.layout', ['title' => 'Clientes y suscripciones · Lorito'])
@section('content')
<section class="card"><div style="display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap"><div><div class="brand">Lorito · Superadministrador</div><h1>Clientes y suscripciones</h1><p class="muted">Sesión de {{ $admin->email }} · cada negocio opera en su propia base de datos.</p></div><form method="post" action="/superadmin/logout">@csrf<button class="secondary">Cerrar sesión</button></form></div>
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<div class="grid" style="margin:18px 0"><div class="notice" style="margin:0"><strong>{{ $tenants->count() }}</strong> clientes registrados</div><div class="notice" style="margin:0"><strong>{{ $tenants->filter(fn($item) => $item->subscription_status === 'trial' && $item->isAvailable())->count() }}</strong> en prueba · <strong>{{ $tenants->filter(fn($item) => $item->subscription_status === 'trial' && !$item->isAvailable())->count() }}</strong> pruebas vencidas · <strong>{{ $tenants->where('subscription_status','active')->count() }}</strong> activos · <strong>{{ $tenants->where('subscription_status','suspended')->count() }}</strong> bloqueados</div></div>
<div class="table-wrap"><div class="tenant tenant-head"><span>Negocio / enlace</span><span>Propietario</span><span>Suscripción</span><span>Administrar</span></div>
@foreach($tenants as $tenant)<article class="tenant"><div><strong>{{ $tenant->name }}</strong><div class="muted">{{ $tenant->slug }}</div><a class="muted" href="{{ url('/?tenant='.$tenant->slug) }}" target="_blank">Abrir negocio ↗</a><div class="muted">DB: {{ $tenant->database_name }}</div></div><div>{{ $tenant->owner_email }}<div class="muted">Creado {{ $tenant->created_at->format('d/m/Y') }}</div></div><div><span class="tag {{ $tenant->subscription_status === 'suspended' || ($tenant->subscription_status === 'trial' && !$tenant->isAvailable()) ? 'suspended' : '' }}">{{ $tenant->subscription_status === 'trial' ? ($tenant->isAvailable() ? 'En prueba' : 'Prueba vencida · bloqueada') : ($tenant->subscription_status === 'active' ? 'Activa' : 'Bloqueada') }}</span><div style="margin-top:7px">{{ $tenant->subscription_plan }} · Q{{ number_format((float)$tenant->subscription_amount,2) }}</div><div class="muted">@if($tenant->subscription_status === 'trial')Prueba hasta {{ $tenant->trial_ends_at?->format('d/m/Y') ?? '—' }}@else Vigente hasta {{ $tenant->subscription_ends_at?->format('d/m/Y') ?? 'sin fecha' }}@endif</div></div><form method="post" action="{{ route('superadmin.subscription', $tenant) }}">@csrf<div class="grid"><label>Estado<select name="subscription_status"><option value="trial" @selected($tenant->subscription_status==='trial')>Prueba gratis</option><option value="active" @selected($tenant->subscription_status==='active')>Activa</option><option value="suspended" @selected($tenant->subscription_status==='suspended')>Bloquear</option></select></label><label>Plan<select name="subscription_plan"><option @selected($tenant->subscription_plan==='Prueba gratis')>Prueba gratis</option><option @selected($tenant->subscription_plan==='Mensual')>Mensual</option><option @selected($tenant->subscription_plan==='Anual')>Anual</option></select></label></div><div class="grid"><label>Precio Q<input name="subscription_amount" type="number" min="0" step="0.01" value="{{ $tenant->subscription_amount }}"></label><label>Vence<input name="subscription_ends_at" type="date" value="{{ $tenant->subscription_ends_at?->format('Y-m-d') }}"></label></div><label>Fin de prueba<input name="trial_ends_at" type="date" value="{{ $tenant->trial_ends_at?->format('Y-m-d') }}"></label><label>Notas de pago<textarea name="subscription_notes" rows="2">{{ $tenant->subscription_notes }}</textarea></label><button style="margin-top:12px">Guardar suscripción</button></form></article>@endforeach
</div></section>
@endsection
